import assert from "node:assert/strict";
import test from "node:test";
import { mkdir, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import ExcelJS from "exceljs";
import JSZip from "jszip";
import { buildApp } from "../../src/app.js";
import { createDatabase } from "../../src/database.js";
import { readConfig } from "../../src/config.js";
import { seedCategories } from "../../prisma/categories.js";
import { startTestDatabase } from "./database.js";

test("Excel export preserves records, exact totals, filters, formulas and charts", { timeout: 120000 }, async (t) => {
  const cluster = await startTestDatabase(); const db = createDatabase(cluster.url);
  const app = buildApp(readConfig({ DATABASE_URL: cluster.url, LOG_LEVEL: "silent" }), { db, clock: () => new Date("2026-09-10T10:00:00Z") });
  t.after(async () => { await app.close(); await db.$disconnect(); await cluster.stop(); });
  await seedCategories(db);
  const food = await db.category.findUniqueOrThrow({ where: { name: "Food & Dining" } });
  const housing = await db.category.findUniqueOrThrow({ where: { name: "Housing" } });
  const transport = await db.category.findUniqueOrThrow({ where: { name: "Transport" } });
  async function create(amount: string, day: string, description: string, split = false, category = food.id) {
    const result = await app.inject({ method: "POST", url: "/transactions", payload: { total_amount: amount, transaction_date: day,
      description, category_id: category, merchant: "Meghana", notes: "=HYPERLINK(\"https://example.com\",\"must stay text\")", is_split: split, participant_count: split ? 3 : null } });
    assert.equal(result.statusCode, 201, result.body);
  }
  await create("1000", "2026-09-03", "Dinner with friends", true);
  await create("500", "2026-09-04", "+Not a formula");
  await create("450", "2026-08-01", "Dinner at Meghana");
  await create("350", "2026-07-05", "Airport ride", false, transport.id);
  const rent = await app.inject({ method: "POST", url: "/recurring-expenses", payload: { name: "Rent", category_id: housing.id, total_amount: "14000", frequency: "monthly", start_date: "2026-09-01" } });
  assert.equal(rent.statusCode, 201);
  await app.inject({ method: "POST", url: `/recurring-expenses/${rent.json().id}/generate`, payload: {} });
  const count = await db.transaction.count();
  const response = await app.inject("/exports/expenses.xlsx?start_date=2026-09-01&end_date=2026-09-30");
  assert.equal(response.statusCode, 200, response.body.slice(0, 100));
  assert.match(String(response.headers["content-type"]), /spreadsheetml/);
  assert.match(String(response.headers["content-disposition"]), /2026-09-01_to_2026-09-30/);
  assert.equal(await db.transaction.count(), count);
  const book = new ExcelJS.Workbook(); await book.xlsx.load(response.rawPayload as unknown as ExcelJS.Buffer);
  assert.deepEqual(book.worksheets.map((sheet) => sheet.name), ["Summary", "Transactions", "Categories", "Monthly"]);
  assert.equal(book.getWorksheet("Summary")!.getCell("A6").result, 14833.33);
  assert.equal(book.getWorksheet("Summary")!.getCell("E6").result, 15500);
  assert.equal(book.getWorksheet("Summary")!.getCell("I6").result, 666.67);
  assert.equal(book.getWorksheet("Summary")!.getCell("A11").result, 833.33);
  assert.equal(book.getWorksheet("Summary")!.getCell("E11").result, 14000);
  assert.equal(book.getWorksheet("Summary")!.getCell("I11").result, 3);
  const rows = book.getWorksheet("Transactions")!;
  assert.equal(rows.getCell("A7").value, "2026-09-01"); assert.equal(rows.getCell("A9").value, "2026-09-04");
  assert.equal(rows.getCell("C9").value, "+Not a formula"); assert.equal(rows.getCell("C9").type, ExcelJS.ValueType.String);
  assert.equal(rows.getCell("N9").type, ExcelJS.ValueType.String); assert.match(String(rows.getCell("N9").value), /^=HYPERLINK/);
  assert.ok(rows.getTable("ExpenseRecords")); assert.equal(rows.views[0]?.state, "frozen");
  assert.equal(book.getWorksheet("Categories")!.getCell("B7").result, 14000);
  assert.equal(book.getWorksheet("Monthly")!.getCell("B7").result, 14833.33);
  const zip = await JSZip.loadAsync(response.rawPayload);
  assert.equal(zip.file(/^xl\/charts\/chart\d+\.xml$/).length, 2);
  assert.match(await zip.file("xl/charts/chart1.xml")!.async("string"), /Categories!\$B\$7/);
  assert.match(await zip.file("xl/worksheets/sheet1.xml")!.async("string"), /drawing r:id="rIdExportCharts"/);
  assert.equal(zip.file(/^xl\/externalLinks\//).length, 0);
  const all = await app.inject("/exports/expenses.xlsx"); assert.equal(all.statusCode, 200);
  const allBook = new ExcelJS.Workbook(); await allBook.xlsx.load(all.rawPayload as unknown as ExcelJS.Buffer);
  assert.equal(allBook.getWorksheet("Summary")!.getCell("I11").result, count);
  const output = resolve("../../Docs/verification"); await mkdir(output, { recursive: true });
  await writeFile(resolve(output, "KharCha_sample_export.xlsx"), all.rawPayload);
  const empty = await app.inject("/exports/expenses.xlsx?start_date=2000-01-01&end_date=2000-01-31");
  assert.equal(empty.statusCode, 200);
  const emptyBook = new ExcelJS.Workbook(); await emptyBook.xlsx.load(empty.rawPayload as unknown as ExcelJS.Buffer);
  assert.equal(emptyBook.getWorksheet("Summary")!.getCell("A6").result, 0);
  assert.match(String(emptyBook.getWorksheet("Summary")!.getCell("A17").value), /No expenses/);
  assert.equal((await app.inject("/exports/expenses.xlsx?start_date=2026-09-01")).statusCode, 400);
  assert.equal((await app.inject("/exports/expenses.xlsx?start_date=2026-09-30&end_date=2026-09-01")).statusCode, 400);
});
